version: 2

# setup dependabot for maintaining npm dependencies
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    # to begin with lets keep the noise low and allow max 1 active version update PRs
    # this will not affect the security update PRs which have an internal limit of 10
    open-pull-requests-limit: 1
    commit-message:
      prefix: "dependency"
      prefix-development: "dev dependency"
    # default PR label 'dependencies'
